name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.16.4'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'automerge, merge, autorelease: tagged, autorelease: pending, !work in progress, !wip'
          MERGE_REMOVE_LABELS: 'automerge, merge'
          MERGE_METHOD: 'merge'
          MERGE_COMMIT_MESSAGE: ':twisted_rightwards_arrows: Merge #{pullRequest.number} ({pullRequest.title})'
          # MERGE_FORKS: false
          # UPDATE_LABELS: 'merge'
          # UPDATE_METHOD: 'merge'
      - name: Delete merged branch
        uses: koj-co/delete-merged-action@master
        with:
          branches: '!main, !production, *'
        env:
          GITHUB_TOKEN: '${{ secrets.GH_PAT }}'
# C:\Users\Susana\Desktop\@github actions [ref]-----\!!!+++++ repo-file-sync-action-master\!!!+++++ github-files-78dde129e83920191669ee7c7afc40fabbb1bc0c\workflows\pull-request
