name: CI
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contribute list in readme.md
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@master
              with:
                  readme_path: "README.md"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
