name: "GitHub banner SVG generator"

on:
  schedule:
  - cron: "* * 1 * *"
  workflow_dispatch:

# permissions:
#   issues: write
#   pull-requests: write
#   repository-projects: write

jobs:
  labelsync:
    name: GitHub banner generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: |
          # npm i -g github-label-sync
          echo "REPOSITORY_NAME=" "$REPOSITORY_NAME"
          echo "REPOSITORY_LANG=" "$REPOSITORY_LANG"
          echo "=" "$"
          echo "=" "$"
          echo "=" "$"
          "$LABEL_CONFIG_PATH" "$LABEL_REPOSITORY"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME : ${{ github.repository }}
          REPOSITORY_LANG : ${{ github.repository.languages }}
          REPOSITORY_STARS : ${{ github.444444 }}
          REPOSITORY_FORKS : ${{ github.444444 }}