name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GITHUB_TOKEN_OPERATIONCARIBBEANSUMMER }}
          PR_LABELS: |
            file-sync
            automerge
          SKIP_PR: true
        group:
          - files:
              - source: .github/workflows/auto-assign.yml
                dest: .github/workflows/auto-assign.yml
            repos: |
              OperationCaribbeanSummer/Jose-Marti-analizer-WikiAgora

      
        # GPL License
        # - files:
        #     - source: .github/workflows/auto-assign.yml
        #       dest: .github/workflows/auto-assign.yml
        #     - source: .eslintignore
        #       dest: .eslintignore
        #   repos: |
        #     OperationCaribbeanSummer/Jose-Marti-analizer-WikiAgora

# PR_LABELS
# SKIP_PR


# user/repo:
#   - source: workflows/build.yml
#     dest: .github/workflows/build.yml
#   - source: LICENSE.md
#     dest: LICENSE

# Sync entire directories
# user/repo:
#   - source: workflows/
#     dest: .github/workflows/

# Sync the same files to multiple repositories
# group:
#   repos: |
#     user/repo
#     user/repo1
#   files: 
#     - source: workflows/build.yml
#       dest: .github/workflows/build.yml
#     - source: LICENSE.md
#       dest: LICENSE

