name: test CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

permissions:
  issues: read

jobs:
  test_report:
    name: test report
    runs-on: ubuntu-latest

    steps:
      - name: Print constants
        shell: bash
        run: |
          # test
